name: Generate Class Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install PlantUML
      run: |
        sudo apt-get update
        sudo apt-get install -y plantuml

    - name: Generate Class Diagram
      run: |
        cd backend
        # Generate PlantUML from C# code (simplified example)
        echo "@startuml
        class Course {
          +Id: int
          +Name: string
          +Description: string
          +InstructorId: int
        }
        class Student {
          +Id: int
          +Name: string
          +Email: string
        }
        class Session {
          +Id: int
          +CourseId: int
          +Date: DateTime
          +Topic: string
        }
        class Attendance {
          +Id: int
          +SessionId: int
          +StudentId: int
          +Status: AttendanceStatus
        }
        Course ||--o{ Session
        Session ||--o{ Attendance
        Student ||--o{ Attendance
        @enduml" > class_diagram.puml
        plantuml class_diagram.puml

    - name: Upload Diagram
      uses: actions/upload-artifact@v4
      with:
        name: class-diagram
        path: backend/class_diagram.png