name: Generate Infrastructure Diagram

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  workflow_dispatch:

jobs:
  diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Generate Diagram
      run: |
        cd terraform
        terraform graph | dot -Tpng > infrastructure.png

    - name: Upload Diagram
      uses: actions/upload-artifact@v4
      with:
        name: infrastructure-diagram
        path: terraform/infrastructure.png